[package]
name = "bull"
version = "0.1.0"
authors = ["semal259 <semalpatel2596@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.9.16"
error-chain = "0.12.1"
console = "0.7.5"
prettytable-rs = "0.8.0"
